# Endereco
#--------------------------------------------------------

###
GET /enderecos/11
Host: localhost:8080

###
POST /enderecos
Host: localhost:8080
Content-Type: application/json

{
	"rua": "Rua das Requisições",
	"numero": 123,
	"cidade": "Uberlândia",
	"estado": "MG",
	"cep": "12345-678"
}

# Pacote
#---------------------------


###
GET /pacotes
Host: localhost:8080

###
POST /pacotes
Host: localhost:8080
Content-Type: application/json

{
		"idUnico": "ABCD1234567",
		"destinatario": "Lucca Henrique",
		"endereco": {
			"id":1
		},
		"status": "pendente"
}

###
GET /pacotes/1
Host: localhost:8080


###
PUT /pacotes/1
Host: localhost:8080
Content-Type: application/json

{
	"status": "em trânsito"
}

# Rastreamento
#----------------------------------------------------
###
GET /rastreamentos/1
Host: localhost:8080


# DELETAR PACOTE
#----------------------------------------------------
###
DELETE /pacotes/1
Host: localhost:8080







